# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idDocente', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fIngreso', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveIntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.docente')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.especialidad')),
            ],
        ),
    ]
