# Generated by Django 4.2.1 on 2023-05-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_alter_docente_fingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idMatricula', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMat', models.DateField()),
                ('cuotas', models.PositiveIntegerField()),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
    ]
